networks:
  compartilha-net:
    external: true

services:
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    container_name: postgres
    networks:
      - compartilha-net
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=compartilha-tech
    volumes:
      - ./.docker/pg-data:/var/lib/postgresql/data

  compartilha-tech:
    container_name: compartilha-tech
    networks:
      - compartilha-net
    build:
      context: compartilha-tech
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./compartilha-tech:/app
    ports:
      - 3333:3333
    depends_on:
      - postgres
