// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
	"time"
)

type MkRegrasVencimento struct {
	Codvenc                int32
	Descricao              sql.NullString
	Tipo                   sql.NullString
	TipoRegra              sql.NullInt32
	TipoPeriodo            sql.NullInt32
	DiaInicio              sql.NullInt32
	DiaVcto                sql.NullInt32
	PreGerarProxMes        sql.NullString
	Inativo                sql.NullString
	DiaReferenciaTelefonia sql.NullInt32
}

type Person struct {
	ID        string
	Name      string
	Age       sql.NullInt32
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
